### ISSUE TITLE
Program does not go past line 91

### ISSUE THREAD

**Issue by PARKTREE7** [kurimawxx00/webota-esp32#3]
Hi! I'd very much appreciate it if you could help me out.

below you can see my serial output;

14:06:51.524 -> ..
14:06:52.075 -> WiFi connected
14:06:52.075 -> IP address: 
14:06:52.075 -> 192.168.178.213
14:06:52.075 -> Response: 200
14:06:52.174 -> FW Size: 4294967295
14:06:52.174 -> Updating firmware...
14:06:52.174 -> ..........................................................................................................................this keeps going for a while but eventually stops

I am unsure why it does not pass line 91. I am getting my .bin from a simple nodejsweb server, it does not seem to provide a content-length which is why "FW Size: " prints out the highest number because in reality it's -1. do you think this might be the issue here, and if so what could I do about it?

I have also tried changing the " if(currentLength != totalLength)" statement so it would pass no matter what after a while, so it is possible, only then when it restarts the ESP it will still be running the same code not that of the .bin....

I am using a ESP32 DEVKITV1.

**Comment by thong9** [comment]
> 

Have you been able to solve this problem?
I have the same problem

**Comment by PARKTREE7** [comment]
unfortunately not, I have switched over to the ESP-IDF, they have a lot of examples on OTA that I actually did get to work. If it's an option for you, I'd suggest you do the same.

**Comment by thong9** [comment]
The problem seems to be in the http path.
please make the path more precise
